compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
dotenv: .env
networks:
  default: development # defaults to development when unspecified
  development:
    verify: false
  kovan:
    verify: true
  ganache-local:
    verify: false
  mainnet-fork:
    verify: false
  mainnet-fork-dev:
    verify: false
  rinkeby:
    verify: true
